/*  Medical Insurance */
export const medicalInsuranceKey = {
  insuranceInfo: 'Insurance Company Name - Insurance ID #',
  companyName: 'Insurance Company Name',
  planOrMedicalGroup: 'Insurance Plan / Medical Group',
  memberName: 'Insured Name',
  memberId: 'Insurance ID #',
  groupNumber: 'Group #',
  relation: 'Relationship to Patient',
  relationAddress: {
    _title: 'Relation',
    line: 'Line',
    secondLine: 'Second Line',
    city: 'City',
    county: 'County',
    state: 'State',
    zipCode: 'Zip Code',
    fullAddress: 'Relation Address',
  },
  gender: 'Gender',
  relationBirth: 'Relation Date of Birth',
  relationName: 'Relation Name',
  claims: {
    _title: 'Claims',
    claimsLine: 'Line',
    claimsSecondLine: 'Second Line',
    claimsCity: 'City',
    claimsCounty: 'County',
    claimsState: 'State',
    claimsZipCode: 'Zip Code',
    claimsFullAddress: 'Claims Address',
  },
  front_InsuranceCardId: 'Front of Insurance Card',
  back_InsuranceCardId: 'Back of Insurance Card',
}

/* Workers Comp */
export const workersCompKey = {
  dateOfInjury: 'Date of Injury',
  employmentInfo: {
    _title: 'Employment Info',
    name: 'Employer Name',
    dept: 'Dept',
    natureOfBusiness: 'Nature of Business.',
    occupation: 'Occupation',
    telephone: 'Telephone #',
    fax: 'Fax #',
    email: 'Email',
    contactName: 'Contact Name',
    contactPhone: 'Contact Phone #',
    companyName: 'Insurance Company Name(Claims Administrator)',
  },
  insurance: {
    _title: 'Insurance',
    claim: 'Claim #',
    claimsAdjuster: 'Claims Adjuster',
    adjusterPhone: 'Adjuster Phone #',
    adjusterFax: 'Adjusters Fax #',
    adjusterEmail: 'Adjusters Email',
    insuranceLine: 'Line',
    insuranceSecondLine: 'Second Line',
    insuranceCity: 'City',
    insuranceCounty: 'County',
    insuranceState: 'State',
    insuranceZipCode: 'Zip Code',
    insuranceFullAddress: 'Insurance Address',
  },
  sendReportTo: {
    _title: 'Send Report To',
    name: 'Name',
    fax: 'Fax',
    email: 'Email',
    line: 'Line',
    secondLine: 'Second Line',
    city: 'City',
    county: 'County',
    state: 'State',
    zipCode: 'Zip Code',
    fullAddress: 'Send Report To Address',
  },
  attorneyInfo: {
    _title: 'Attorneys Info',
    name: 'Attorney Name',
    phone: 'Phone #',
    fax: 'Fax #',
    email: 'Email',
    attorneyLine: 'Line',
    attorneySecondLine: 'Second Line',
    attorneyCity: 'City',
    attorneyCounty: 'County',
    attorneyState: 'State',
    attorneyZipCode: 'Zip Code',
    attorneyFullAddress: 'Attorney Info Address',
    contactName: 'Contact Name',
  },
}

/* Personal Injury */
export const personInjuryKey = {
  dateOfInjury: 'Date of Injury',
  attorneyInfo: {
    _title: 'Attorneys Info',
    name: 'Attorneys Name',
    phone: 'Phone #',
    fax: 'Fax #',
    email: 'Email',
    line: 'Line',
    secondLine: 'Second Line',
    city: 'City',
    county: 'County',
    state: 'State',
    zipCode: 'Zip Code',
    fullAddress: 'Attorney Info Address',
    contactName: 'Contact Name',
  },
}

export const pateintProfileKey = {
  basicInfo: {
    _title: 'Basic Info',
    dateOfBirth: 'Date of Birth',
    firstName: 'First Name',
    fullName: 'Full Name',
    gender: 'Gender',
    lastName: 'Last Name',
    middleName: 'Middle Name',
    socialSecurity: 'Social Security # ',
    myEmail: 'My Email ',
    avatar: 'Avatar',
    phone: "Full Phone"
  },
  contactInfo: {
    _title: 'Contact Info',
    line: 'Address Line',
    secondLine: 'Address Second Line',
    city: 'City',
    county: 'County',
    state: 'State',
    zipCode: 'Zip code',
    fullAddress: 'Contact Address',
    fullPhone: 'Alternate Phone # ',
    countryCode: "Country Code",
    phoneNumber: "Phone Number",
    email: 'Other Email',
  },
  identification: {
    _title: 'Identification',
    id: 'ID #',
    imageId: 'ID Image',
    type: 'ID Type',
  },
  emergencyContact: {
    _title: 'Emergency Contact',
    emergencyFirstName: 'First Name',
    emergencyMiddleName: 'Middle Name',
    emergencyLastName: 'Last Name',
    relation: 'Relation',
    emergencyCountryCode: 'Country Code',
    emergencyPhoneNumber: 'Phone Number',
    emergencyFullPhone: 'Full Phone',
  },
}
